### ISSUE TITLE
Not using individual multipliers.

### ISSUE THREAD

**Issue by FrostyWolf** [attrib/RepairRecipe#17]
Config: http://pastebin.com/ktxWjknm
Output: http://pastebin.com/hWnhkKjy

I believe I have the config set properly...but it is still using a .5 enchant multi instead of a .25 for diamond_helmet.

Also, I just release I have over_repair set to true and it says false there.

Ha, I just realized I should be doing that in items.yml, that's my mistake.

Also, I got over repair to work...but I had to install a permissions plug in, is this intended?

**Comment by attrib** [comment]
I will have a look into it, why the plugin doesn't use the enchant multi from the item.yml.

Added #22 for the 'allow_over_repair' bug.

**Comment by FrostyWolf** [comment]
No no, you can close this one.  It was because I put them in config.yml instead of item.yml.

The over_repair issue is real tho.

**Comment by attrib** [comment]
Then closing this.
Anyways thanks for the reports.
