### ISSUE TITLE
ru.tehkode.permissions.exceptions.PermissionsNotAvailable 

### ISSUE THREAD

**Issue by Vereor** [attrib/RepairRecipe#28]
I am getting the below error when bukkit tried to load the plugin.

[SEVERE] Error occurred while enabling RepairRecipe v0.4.7-beta (Is it up to date?) java.lang.ClassNotFoundException: ru.tehkode.permissions.exceptions.PermissionsNotAvailable

Running CB 1.5.2-R0.1 | GroupManager v2.0 (Pre2.11.1.5) (Phoenix) | Vault v1.2.25-b320

Many people commenting on bukkitdev are getting a similar error.

**Comment by attrib** [comment]
Thanks for posting the issue.
Hopefully this is fixed now.
Sorry it took so long. Very busy currently.
See bukkit page for new build - takes some time till its approved.
