### ISSUE TITLE
MCPC custom items error

### ISSUE THREAD

**Issue by giovanni-bozzano** [attrib/RepairRecipe#29]
I get this error in the console every time I put in and out of the workbench a custom base repair item:

http://pastebin.com/TZN2aDyY

The error is related to the events, but I wasn't able to figure out what to edit in the code.
Any suggestion? :)

**Comment by attrib** [comment]
Can you paste your items.yml?
Do you have a line with `base_amount: 0`?

**Comment by giovanni-bozzano** [comment]
Here it is:

http://pastebin.com/bwBPBPcU

I just added the last three custom swords and metal dusts from Metallurgy 3.1.1.

**Comment by attrib** [comment]
What Plugin do you use for the custom items cooper and steel at the end of the items.yml?
Please provide a link to the plugin and maybe a very easy base config for it.

**Comment by giovanni-bozzano** [comment]
I use the mod Metallurgy 3.1.1 with the last version of MCPC Plus server 1.5.2.

**Comment by giovanni-bozzano** [comment]
Anyway, every mod item is giving this error, but just on console, everything is working as it should.

**Comment by attrib** [comment]
Okay I wanted to check it out today, but didin't get Metallurgy to run, as it is not a normal Bukkit plugin.
I don't want to take the time to figure out how I can get this to run.
If you want to use my Plugin with MCPC (?) and Metallurgy please provide me a download link to a minimal configured server and probably client too. I want to help you but I don't want to waste 2 hours configure a server just to run my tests to fix this and never use it again.

**Comment by giovanni-bozzano** [comment]
Ok, I'm going to make a premade pack to simulate the error and give it to you tomorrow morning (it's late night here). _yawn_

MCPC is growing in popularity as it combines the power of Bukkit API with Forge.
That means less security on servers, but I run it on a network with a launcher that checks every file's md5 to see if they are modified for every server in the list and, obviously, source edited clients and servers to let users connect only through the launcher; a private account manager and skinserver and other pretty awesome things..

**Comment by giovanni-bozzano** [comment]
https://mega.co.nz/#!x0hlAaQZ!C1QwgiLjcyVo9A7fJ6eKXxtUIOAXvbcZETZjtCOWkXE

Here it is. I just deleted some of the auto-generating files to make it smaller.
I also added the recipe to repair the "Copper Sword" with "Copper Dust" in the plugin configuration. As soon as you put the dust into and out the workbench, the console spams out that error.

**Comment by attrib** [comment]
Thanks for that, but no good news.
Either in Forge or Metallurgy is a Bug. The max durabillity is not set correctly and always 0.  If I don't know the max durabillity of a item type I can't calculate how much base items are needed. I tried to talk with the Metallurgy guys in IRC, but they couldn't help me and the response was very low. I created a issue for this in Metallurgy.
As long as this is not fixed I can't help you :(

**Comment by giovanni-bozzano** [comment]
No problem, if the issue isn't solved I'll just ignore the error as the item gets repaired. Thank's for your help. :D

**Comment by am4ii** [comment]
I'm trying to make this plugin to work with metallurgy to But I use the item name for items.yml like
x26512:
  base_item: x26506
  base amount: 2
I dont see anything on console beside the start up error if the plugin is up to date. Nothing on console too when I put the items on the workbench, then again I haven tried repairing items since I'm having permission issue with bPermissions,

**Comment by attrib** [comment]
@am4ii If you get the error "plugin is up to date" it is something noticeable! So it seems something completely different than this issue was original about! Which version of RepairRecipe and which version of Bukkit do you use?

**Comment by am4ii** [comment]
@attrib I use RepairRecipe v0.4.9-beta and mcpc-plus-1.6.2-R0.2-forge836-B55. I comment here since the first guy uses MCPC+ with metallurgy such as I.

**Comment by giovanni-bozzano** [comment]
Thank you, as soon as I update my server to 1.6, I'll try that.
